version: "2"
run:
  tests: true
linters:
  enable:
    - dupl
    - gocritic
    - gosec
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G204
        - G301
        - G306
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
