version: "2"

run:
  tests: true
  timeout: 5m

linters:
  enable:
    - dupl
    - errcheck
    - gocritic
    - govet
    - misspell
    - prealloc
    - staticcheck
    - unconvert
    - unparam
  disable:
    - gosec  # Disabled due to overly strict file permission checks
    - revive  # Disabled due to false positives on package naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
