# GoReleaser configuration
# Documentation: https://goreleaser.com
version: 2
before:
  hooks:
    # Clean up before building
    - go mod tidy
    - go mod verify
builds:
  - id: compose2podman
    main: ./cmd/compose2podman
    binary: compose2podman
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      # - freebsd
    goarch:
      - amd64
      - arm64
      # - arm
      # - "386"
    goarm:
      # - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    flags:
      - -trimpath
archives:
  - id: compose2podman
    name_template: >-
      {{ .ProjectName }}_ {{- .Version }}_ {{- .Os }}_ {{- .Arch }} {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - QUICKSTART.md
      - EXAMPLES.md
      - CONTRIBUTING.md
      - testdata/*
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*enhancement[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
release:
  github:
    owner: kad
    name: compose2podman
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## compose2podman {{.Version}}

    > **⚠️ PROOF-OF-CONCEPT / NOT FOR PRODUCTION USE ⚠️**
    >
    > This project is a **proof-of-concept** tool completely generated by GitHub Copilot.
    > **NOT tested with real-world data. NOT intended for production environments.**
    > Use at your own risk for experimental purposes only. Always verify generated configurations.
    > For production use, consider [podman-compose](https://github.com/containers/podman-compose).

    Docker Compose to Podman converter - Generate Kubernetes Pod YAML or Podman Quadlet files.

    ### Installation

    **Linux (amd64):**
    ```bash
    wget https://github.com/kad/compose2podman/releases/download/v{{.Version}}/compose2podman_{{.Version}}_linux_amd64.tar.gz
    tar -xzf compose2podman_{{.Version}}_linux_amd64.tar.gz
    sudo mv compose2podman /usr/local/bin/
    ```

    **macOS (arm64/amd64):**
    ```bash
    wget https://github.com/kad/compose2podman/releases/download/v{{.Version}}/compose2podman_{{.Version}}_darwin_arm64.tar.gz
    tar -xzf compose2podman_{{.Version}}_darwin_arm64.tar.gz
    sudo mv compose2podman /usr/local/bin/
    ```

    **Windows:**
    Download the `.zip` file for your architecture and extract it.

    **From package manager:** See installation instructions below.
  footer: |
    ---

    ### ⚠️ Important Notice

    This is a **proof-of-concept tool** generated by GitHub Copilot. It has **NOT been thoroughly tested**
    with real-world Docker Compose files and is **NOT intended for production use**. Always manually verify
    the generated output before using it in any environment.

    ---

    **Full Changelog**: https://github.com/kad/compose2podman/compare/{{.PreviousTag}}...v{{.Version}}

    ### Verifying the Installation

    ```bash
    compose2podman -version
    ```
# Linux packages
nfpms:
  - id: compose2podman
    package_name: compose2podman
    vendor: compose2podman contributors
    homepage: https://github.com/kad/compose2podman
    maintainer: compose2podman contributors
    description: |
      Convert Docker Compose files to Podman formats.
      Supports Kubernetes Pod YAML and Podman Quadlet generation.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/compose2podman/LICENSE
      - src: README.md
        dst: /usr/share/doc/compose2podman/README.md
      - src: QUICKSTART.md
        dst: /usr/share/doc/compose2podman/QUICKSTART.md
      - src: EXAMPLES.md
        dst: /usr/share/doc/compose2podman/EXAMPLES.md
      - src: testdata/simple.yaml
        dst: /usr/share/doc/compose2podman/examples/simple.yaml
      - src: testdata/docker-compose.yaml
        dst: /usr/share/doc/compose2podman/examples/docker-compose.yaml
    dependencies:
      - podman
    recommends:
      - systemd
    rpm:
      group: Development/Tools
      compression: lzma
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    archlinux:
      packager: compose2podman contributors
# Homebrew tap (renamed from brews)
# Uncomment and configure when ready to publish to Homebrew
# homebrew:
#   - name: compose2podman
#     repository:
#       owner: kad
#       name: homebrew-tap
#       branch: main
#       token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#     directory: Formula
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     homepage: https://github.com/kad/compose2podman
#     description: Convert Docker Compose files to Podman formats
#     license: MIT
#     skip_upload: auto
#     test: |
#       system "#{bin}/compose2podman", "-version"
#     install: |
#       bin.install "compose2podman"
#       doc.install "README.md"
#       doc.install "QUICKSTART.md"
#       doc.install "EXAMPLES.md"

# Snapcraft (Ubuntu Snap)
snapcrafts:
  - name: compose2podman
    publish: false
    disable: true
    summary: Convert Docker Compose files to Podman formats
    description: |
      compose2podman is a CLI tool that converts Docker Compose files to
      Podman-compatible formats including Kubernetes Pod YAML and Podman Quadlet files.
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    apps:
      compose2podman:
        command: compose2podman
        plugs:
          - home
          - network
          - removable-media
# Docker images (optional, if you want to provide the tool as a container)
# Disabled by default - enable by uncommenting and setting up Docker
# dockers:
#   - image_templates:
#       - "ghcr.io/kad/compose2podman:{{ .Version }}-amd64"
#       - "ghcr.io/kad/compose2podman:latest-amd64"
#     use: buildx
#     goos: linux
#     goarch: amd64
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source=https://github.com/kad/compose2podman"
#     dockerfile: Dockerfile
#     skip_push: auto

#   - image_templates:
#       - "ghcr.io/kad/compose2podman:{{ .Version }}-arm64"
#       - "ghcr.io/kad/compose2podman:latest-arm64"
#     use: buildx
#     goos: linux
#     goarch: arm64
#     build_flag_templates:
#       - "--platform=linux/arm64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source=https://github.com/kad/compose2podman"
#     dockerfile: Dockerfile
#     skip_push: auto

# docker_manifests:
#   - name_template: "ghcr.io/kad/compose2podman:{{ .Version }}"
#     image_templates:
#       - "ghcr.io/kad/compose2podman:{{ .Version }}-amd64"
#       - "ghcr.io/kad/compose2podman:{{ .Version }}-arm64"
#     skip_push: auto

#   - name_template: "ghcr.io/kad/compose2podman:latest"
#     image_templates:
#       - "ghcr.io/kad/compose2podman:latest-amd64"
#       - "ghcr.io/kad/compose2podman:latest-arm64"
#     skip_push: auto

# Announce to social media (optional)
announce:
  skip: "{{gt .Patch 0}}" # Skip patch releases

# Signs the checksums file (optional - only when GPG is configured)
# signs:
#   - cmd: gpg
#     signature: "${artifact}.sig"
#     artifacts: checksum

# GitHub Sponsors integration (optional)
# funding:
#   - github: kad
